### ISSUE TITLE
responsive   GUI wireframe (split into subtasks so not weighted)

### ISSUE THREAD

**Issue by kimberlyl26** [USStateDept/search#488]

**Comment by kimberlyl26** [comment]
So far
[guiguigui_responsive.zip](https://github.com/USStateDept/search/files/606565/guiguigui_responsive.zip)

**Comment by kimberlyl26** [comment]
- [x] Left sidebar stacks and centers at top at certain width because of bootstrap. Made this collapsible only for this  sizes <= the width and collapsed by default (for each version   ).  #495
- [x] Fix spacing with 'Help Me Find Something' url under logo. #496
- [ ] Make top matches side bar  for version 2 stack at the top when in mobile view instead of at the bottom
- [x] Add expand/collapse functionality to the 'show more' in filter options for both responsive  and non responsive #494
- [x] Add the footer. #497

What i've got so far: 
[gui.zip](https://github.com/USStateDept/search/files/609513/gui.zip)
