### ISSUE TITLE
Elasticsearch API Service

### ISSUE THREAD

**Issue by captjt** [USStateDept/search#533]
- [x] Create barebone skeleton service (pre-data) [#534](https://github.com/USStateDept/search/issues/534)
- [x] Flush out first iteration of structure query for indexed data [#535](https://github.com/USStateDept/search/issues/535)
- [x] Create more search query endpoints to test results from other aggregated queries [#544](https://github.com/USStateDept/search/issues/544)
- [x] Add highlighting integration with querying results on all endpoints [#545](https://github.com/USStateDept/search/issues/545)
