### ISSUE TITLE
Crawler Prototype Service

### ISSUE THREAD

**Issue by captjt** [USStateDept/search#547]
The crawler will need to be able to set a starting point and effectively crawl through pages/links to documents/forms/etc. and fire off scraping jobs for the sources.

### Tasks

- [x] Create generic crawling application [#548](https://github.com/USStateDept/search/issues/548)
- [x] Combine the scraping and crawling aspects [#555](https://github.com/USStateDept/search/issues/555)
- [x] Index/ingest scraped data into Elasticsearch [#554](https://github.com/USStateDept/search/issues/554)
- [x] Monitoring some memory usage [#558](https://github.com/USStateDept/search/issues/558)
- [x] Create custom settings (User Agent, Crawl Delays, WorkersTTL)

### Post-Working Prototype
- [x] Time constraint checking for full scan of state.gov [#560](https://github.com/USStateDept/search/issues/560)
- [x] Convert the ingestion to transaction based storage [#561](https://github.com/USStateDept/search/issues/561)

#### Scraping Checklist
**Job Types**
- [x] HTML
